### ISSUE TITLE
[v0.9] login-service is not fully customizable

### ISSUE THREAD

**Issue by gpavone** [EOEPCA/eoepca#53]
In `v0.9` it is still not possible to configure the `login-service` properly.

According to the `login-service` helm chart (e.g. https://github.com/EOEPCA/helm-charts/blob/login-service-0.9.0/charts/login-service/values.yaml), we should be able to customize parameters like `countryCode`, `state`, `city`, `orgName`, etc. but if we do so the Gluu instance is not installed correctly and does not start (an error page is shown).

We tried to overcome the issue by replacing the TLS certificate used by Gluu with a new one generated using our data, but it did not work (`oxauth` pod could not restart).

**Comment by rconway** [comment]
Created as user story EOEPCA-460 - https://eoepca.atlassian.net/browse/EOEPCA-460

**Comment by rconway** [comment]
EOEPCA-460 has been implemented to resolve this issue, and is included in eoepca release v1.0.
