### ISSUE TITLE
[v0.9] Helm charts config reference not very helpful

### ISSUE THREAD

**Issue by gpavone** [EOEPCA/eoepca#54]
The helm charts config reference (https://github.com/EOEPCA/eoepca/tree/v0.9/system/clusters/creodias) for the cluster deployment forces the service operator to use `flux` and other dependencies he may not want to use in his infrastructure.

It would be nice to have a platform-independent helm chart configuration that allows the service operator to deploy the building blocks in any empty kubernetes cluster.

Moreover, it would be really appreciated to have some documentation for the helm charts, explaining the purpose of each parameter so that the service operator would be able to properly configure the building blocks within his infrastructure.

**Comment by rconway** [comment]
The `eoepca` deployments are provided as examples. Most components are deployed using their helm charts, with the flux `HelmRelease` providing examples of the values to supply to create a the helm release. Those not wishing to use flux can easily extract the values from these HelmReleases, which must be tailored to their operational environment.

The helm charts themselves are independently hosted at the EOEPCA helm chart repository - https://eoepca.github.io/helm-charts/index.yaml.

The deficiency in the helm chart documentation is understood, with a number of existing stories to address this:
- ADES - EOEPCA-435 - https://eoepca.atlassian.net/browse/EOEPCA-435
- Login Service - EOEPCA-436 - https://eoepca.atlassian.net/browse/EOEPCA-436
- PDP - EOEPCA-437 - https://eoepca.atlassian.net/browse/EOEPCA-437
- PEP - EOEPCA-438 - https://eoepca.atlassian.net/browse/EOEPCA-438
- User Workspace - EOEPCA-440 - https://eoepca.atlassian.net/browse/EOEPCA-440
- User Profile - EOEPCA-441 - https://eoepca.atlassian.net/browse/EOEPCA-441
- Workspace API - EOEPCA-442 - https://eoepca.atlassian.net/browse/EOEPCA-442
- Data Access - EOEPCA-443 - https://eoepca.atlassian.net/browse/EOEPCA-443
- Bucket Operator - EOEPCA-461 - https://eoepca.atlassian.net/browse/EOEPCA-461

**Comment by rconway** [comment]
With eoepca release v1.0, each of the helm charts (as per above) are now supported by a README that describes their values - with the exception of the Bucket Operator for which there is not yet a helm chart.

In addition, the Deployment Guide (https://deployment-guide.docs.eoepca.org/) has been published to provide a description of the BB deployments using helm charts directly (not flux), and should be regarded as a good reference. Within this guide links are provided to the specific 'values' documentation for each helm chart.
