### ISSUE TITLE
[v0.9] No helm chart for workspace-api and bucket-operator

### ISSUE THREAD

**Issue by gpavone** [EOEPCA/eoepca#55]
It would be very nice to have an helm chart for every building block when a new release is published.

`v0.9` did not include any helm chart for the services `workspace-api` and `bucket-operator`, which forced us to duplicate and properly customize the kubernetes manifests in order to deploy those services on our cluster.
As you can imagine, this can lead to several misconfigurations since the service operator does not really know the internal logic of the building block.

Moreover, as for the `bucket-operator`, the deployment manifest still uses an image reference which points to a private docker registry, not accessible to the service operator.

**Comment by rconway** [comment]
**Workspace API**
There is an existing story (EOEPCA-442) regarding the provision of a helm chart for the Workspace API - https://eoepca.atlassian.net/browse/EOEPCA-442.

**Bucket Operator**
Story EOEPCA-461 has been created regarding the helm chart - https://eoepca.atlassian.net/browse/EOEPCA-461.

**Private Docker Registry**
Story EOEPCA-462 has been created for this aspect - https://eoepca.atlassian.net/browse/EOEPCA-462.

**Comment by rconway** [comment]
There is now a helm chart for the Workspace API (ref. EOEPCA-442):
- Helm chart: https://github.com/EOEPCA/helm-charts/tree/main/charts/rm-workspace-api
- Deployment: https://deployment-guide.docs.eoepca.org/workspace/#workspace-api

**Comment by rconway** [comment]
Helm charts have now been created:

- Workspace API - https://github.com/EOEPCA/helm-charts/tree/eoepca-v1.1/charts/rm-workspace-api
- Bucket Operator - https://github.com/EOEPCA/helm-charts/tree/eoepca-v1.1/charts/rm-bucket-operator
