### ISSUE TITLE
Umbrella chart for a complete deployment?

### ISSUE THREAD

**Issue by fabricebrito** [EOEPCA/eoepca#56]
I've searched for an umbrella chart gathering all EOEPCA building blocks to ease their deployment but could not find it.

Current behaviour: 

- individual charts 

Expected/desired behaviour:

- an umbrella chart + values for simplifying the deployment of all building blocks on a k8s cluster

**Comment by rconway** [comment]
EOEPCA Jira issue EOEPCA-525 has been created for this - https://eoepca.atlassian.net/browse/EOEPCA-525

**Comment by fabricebrito** [comment]
We decided to go for the ArgoCD app of apps pattern
