### ISSUE TITLE
[v1.0] Helm charts are incompatible with recent Kubernetes versions

### ISSUE THREAD

**Issue by bevalentin** [EOEPCA/eoepca#60]
Helm charts use in particular Kubernetes API versions `extensions/v1beta1` and `networking.k8s.io/v1beta1`.

These have been marked as *deprecated* in Kubernetes v1.16 in July 2019 [1] and eventually *removed* in v1.22 in July 2021 [2].

The EOEPCA Deployment Guide mentions two old Kubernetes versions (v1.18.10 and v1.21.5). Both still implement the beta APIs [3].

The Guide also indicates that API version `networking.k8s.io/v1` must be used for creating nginx ingresses (in [4]). This API version must be used to make EOEPCA building blocks compatible with recent Kubernetes installations.

Bernard

[1] https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
[2] https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/
[3] https://deployment-guide.docs.eoepca.org/kubernetes/
[4] https://deployment-guide.docs.eoepca.org/cluster-prerequisites/

**Comment by rconway** [comment]
Thanks for the feedback - I'll raise this for discussion with the team.
Kubernetes is a moving target, so we need to decide how we support this. Thus far we have been fixed on v1.18 within our development - this is reflected in our current helm/yaml.

**Comment by rconway** [comment]
With eoepca release v1.1 all building blocks were updated for Kubernetes v1.22.x - the latest stable release at time of release preparation.
