### ISSUE TITLE
Use custom namespace for Container Registry

### ISSUE THREAD

**Issue by ghost** [EOEPCA/eoepca#73]
According to the [deployment guide](https://deployment-guide.docs.eoepca.org/current/eoepca/container-registry/#helm-chart), the Container Registry should be installed in the default namespace.

Is is possible installed in another namespace?

**Comment by rconway** [comment]
It is not necessary to deploy harbor to the default namespace. I don't think the Deployment Guide says this - although the example command does not specify a namespace - the choice of namespace is left to the reader.

For example, our `develop` cluster deploys harbor to the `rm` namespace - https://github.com/EOEPCA/eoepca/blob/develop/system/clusters/creodias/resource-management/hr-harbor.yaml#L5
